### ISSUE TITLE
java.lang.OutOfMemoryError when activating ShowEditorOnlyAction

### ISSUE THREAD

**Issue by markiewb** [Chris2011/nb-codeoutline#11]
```
SEVERE [global]
java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
    at java.awt.image.Raster.createPackedRaster(Raster.java:467)
    at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
    at java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:186)
    at bluej.editor.moe.NaviView.paintImgBuffer(NaviView.java:385)
    at bluej.editor.moe.NaviView.createImgBuffer(NaviView.java:609)
    at bluej.editor.moe.NaviView.setBounds(NaviView.java:177)
    at javax.swing.BoxLayout.layoutContainer(BoxLayout.java:447)
    at java.awt.Container.layout(Container.java:1508)
    at java.awt.Container.doLayout(Container.java:1497)
    at java.awt.Container.validateTree(Container.java:1693)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validate(Container.java:1628)
    at javax.swing.JLayeredPane.addImpl(JLayeredPane.java:232)
    at java.awt.Container.add(Container.java:971)
    at javax.swing.JRootPane.setContentPane(JRootPane.java:626)
    at javax.swing.JFrame.setContentPane(JFrame.java:695)
    at org.netbeans.core.windows.EditorOnlyDisplayer.activate(EditorOnlyDisplayer.java:199)
    at org.netbeans.core.windows.EditorOnlyDisplayer.setActive(EditorOnlyDisplayer.java:105)
    at org.netbeans.core.windows.actions.ShowEditorOnlyAction.actionPerformed(ShowEditorOnlyAction.java:117)
    at org.openide.windows.TopComponent.processKeyBinding(TopComponent.java:1176)
    at javax.swing.JComponent.processKeyBindings(JComponent.java:2940)
    at javax.swing.JComponent.processKeyEvent(JComponent.java:2842)
    at java.awt.Component.processEvent(Component.java:6302)
    at java.awt.Container.processEvent(Container.java:2234)
[catch] at java.awt.Component.dispatchEventImpl(Component.java:4881)
```

**Comment by markiewb** [comment]
I hope it is fixed in 1.2.0
