### ISSUE TITLE
java.lang.ArithmeticException: / by zero     at bluej.editor.moe.NaviView.adjustmentValueChanged(NaviView.java:236)

### ISSUE THREAD

**Issue by markiewb** [Chris2011/nb-codeoutline#14]
```
WARNING [org.openide.windows.WindowManager]: [Winsys] TopComponent org.netbeans.core.multiview.MultiViewCloneableTopComponent throws exception/error from its componentClosed() method.
Please repair it!
java.lang.ArithmeticException: / by zero
    at bluej.editor.moe.NaviView.adjustmentValueChanged(NaviView.java:236)
    at javax.swing.JScrollBar.fireAdjustmentValueChanged(JScrollBar.java:705)
    at javax.swing.JScrollBar.access$100(JScrollBar.java:81)
    at javax.swing.JScrollBar$ModelListener.stateChanged(JScrollBar.java:727)
    at javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:364)
    at javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:302)
    at javax.swing.JScrollBar.setValues(JScrollBar.java:623)
    at javax.swing.plaf.basic.BasicScrollPaneUI.syncScrollPaneWithViewport(BasicScrollPaneUI.java:285)
    at javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1033)
    at javax.swing.JViewport.fireStateChanged(JViewport.java:1369)
    at javax.swing.JViewport.setViewSize(JViewport.java:1021)
    at javax.swing.ViewportLayout.layoutContainer(ViewportLayout.java:201)
    at java.awt.Container.layout(Container.java:1508)
    at java.awt.Container.doLayout(Container.java:1497)
    at java.awt.Container.validateTree(Container.java:1693)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validate(Container.java:1628)
    at java.awt.CardLayout.showDefaultComponent(CardLayout.java:488)
    at java.awt.CardLayout.next(CardLayout.java:454)
    at java.awt.CardLayout.removeLayoutComponent(CardLayout.java:248)
    at java.awt.Container.removeAll(Container.java:1298)
    at org.netbeans.core.multiview.TabsComponent.peerComponentClosed(TabsComponent.java:527)
    at org.netbeans.core.multiview.MultiViewPeer.peerComponentClosed(MultiViewPeer.java:331)
    at org.netbeans.core.multiview.MultiViewCloneableTopComponent.componentClosed(MultiViewCloneableTopComponent.java:129)
[catch] at org.openide.windows.WindowManager.componentCloseNotify(WindowManager.java:322)
    at org.netbeans.core.windows.WindowManagerImpl.notifyTopComponentClosed(WindowManagerImpl.java:1156)
    at org.netbeans.core.windows.Central.removeModeTopComponent(Central.java:1025)
    at org.netbeans.core.windows.ModeImpl.removeTopComponent(ModeImpl.java:478)
    at org.netbeans.core.windows.ModeImpl.close(ModeImpl.java:286)
    at org.netbeans.core.windows.WindowManagerImpl.topComponentClose(WindowManagerImpl.java:1321)
    at org.openide.windows.TopComponent.close(TopComponent.java:561)
    at org.openide.windows.TopComponent.close(TopComponent.java:548)
    at org.netbeans.core.windows.actions.ActionUtils$1.run(ActionUtils.java:515)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by markiewb** [comment]
I hope it is fixed in 1.2.0
