### ISSUE TITLE
java.lang.NullPointerException    at javax.swing.text.JTextComponent.setDocument(JTextComponent.java:440)

### ISSUE THREAD

**Issue by markiewb** [Chris2011/nb-codeoutline#19]
Taken from https://netbeans.org/bugzilla/show_bug.cgi?id=250229

```
java.lang.NullPointerException
   at javax.swing.text.JTextComponent.setDocument(JTextComponent.java:440)
   at bluej.editor.moe.NVDrawPane.setDocument(NVDrawPane.java:64)
   at bluej.editor.moe.NaviView.setDocument(NaviView.java:106)
   at bluej.editor.moe.NaviView.<init>(NaviView.java:90)
   at de.markiewb.netbeans.plugins.outline.OutlineTopComponent.resultChanged(OutlineTopComponent.java:103)
   at org.openide.util.lookup.SimpleProxyLookup.checkLookup(SimpleProxyLookup.java:114)
```

**Comment by markiewb** [comment]
OutlineTopComponent does not anymore since 1.2.0. So closing as invalid
